### ISSUE TITLE
Need support FontIconInfo for MenuFlyouts 

### ISSUE THREAD

**Issue by jechternach** [microsoft/react-native-xaml#145]
### Problem Description

When using MenuFlyout there does not seem to be a property exposed to support FontIconInfo in menuFlyouts. We are trying to display glyphs with MenuFlyoutItems. It could be we are unaware of a possible workaround or a property that were unaware of. 

### Steps To Reproduce

Render a MenuFlyout and MenuFlyoutItem, try and find fontIconInfo property or anything related.
Also tried to render a  `<FontIcon glyph="&#xE790;" />` as a child of MenuFlyoutItem and that did not work  

### Expected Results

Ability to display WinUI Glyphs 

### Environment

```markdown
npx react-native info
```

**Comment by asklar** [comment]
@chiaramooney this would be a good one to start ramping up on
