### ISSUE TITLE
MenuFlyout isOpen property is not respected 

### ISSUE THREAD

**Issue by jechternach** [microsoft/react-native-xaml#146]
### Problem Description

Trying to only open MenuFlyout once a specific condition is met, I thought that I could use the `isOpen = {condition}` property but the flyout does not seem to respect it. For example, if I set `isOpen = {false}` the flyout still opens when I right click on the item it is attached too. 

### Steps To Reproduce

`<GridViewItem> 
    <Grid></Grid>
    <MenuFlyout
        isOpen = {false}
    > 
        <MenuFlyoutItem text = "some flyout item"/>
    </MenuFlyout>
</GridViewItem>`

I would expect running this code would create a flyout that never opens? But it does open whenever the `onRightTapped` event is activated

### Expected Results

Very possible I am incorrectly using the MenuFlyout? I would like there to be a way to ideally create a flyout programmatically without having to add it to the XAML tree, but having the MenuFlyout only open once a condition is met seemed like the next best option

### Environment

```markdown
npx react-native info
```

**Comment by asklar** [comment]
This is on par with how MenuFlyout in xaml behaves when used as a ContextFlyout:

https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.MenuFlyout?view=winrt-22000

![image](https://user-images.githubusercontent.com/22989529/140440143-3c803bcf-107a-4994-b34f-3c92a65ec13e.png)


I think the first step would be to figure out how you would do what you want in XAML and then we can see how it translates to react-native

**Comment by asklar** [comment]
I think in XAML you wouldn't use a ContextFlyout, but instead you'd use AttachedFlyout, and call ShowAt programmatically in code behind in response to some event
