### ISSUE TITLE
Add ActionButton inside the InfoBar

### ISSUE THREAD

**Issue by shreyaspadhye3011** [microsoft/react-native-xaml#160]
Need: Many solutions require the presence of an action button inside the InfoBar. For example, when the InfoBar is suggesting an expired log in and the action button is a CTA to "Log In" to refresh access. (Fyi: For the current use case, I need the action button to open an external URL)

Can this be added?

**Comment by chrisglein** [comment]
@shreyaspadhye3011 Can you include some example code of what you expect to be able to do here?
I assume we're talking about [this InfoBar](https://docs.microsoft.com/en-us/windows/apps/design/controls/infobar) and [this ActionButton property](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.infobar.actionbutton?view=winui-3.0)? None of the examples in XAML Controls Gallery demonstrate the `ActionButton`.

**Comment by shreyaspadhye3011** [comment]
@chrisglein This is in reference to the related [WinUI.InfoBar](https://github.com/microsoft/react-native-xaml/blob/main/USAGE.md#infobar) defined in react-native-xaml. The links you mentioned above are the correct XAML counterparts.

I want to be able to do something like:
```
   <WinUI.InfoBar
        message={"Your profile information is out of date. Please update now."}
        isOpen={true}
        visibility={Visibility.Visible}
        isClosable={true}
        severity={WinUIEnums.InfoBarSeverity.Warning}
        style={{ marginBottom: 5 }}
        actionButtonText="Update"
        onActionButtonClick={e => {
           console.log('button clicked');
           // add business logic on button action
        }}
      />
```

Currently, I don't see a way to include an action button inside the InfoBar which is super useful when you want the end-user to take action right away. Hope this helps clarify the requirement.

**Comment by asklar** [comment]
I expect the design for this will be slightly different:
```xml
   <WinUI.InfoBar
        message={"Your profile information is out of date. Please update now."}
        isOpen={true}
        visibility={Visibility.Visible}
        isClosable={true}
        severity={WinUIEnums.InfoBarSeverity.Warning}
        style={{ marginBottom: 5 }}
      >
      <Button priority={WinUIEnums.InfoBarPriority.ActionButton}
        content="Update"
        onClick={e => {
           console.log('button clicked');
           // add business logic on button action
        }} />
    />
```

**Comment by shreyaspadhye3011** [comment]
I agree with the proposed design. Much more flexible. Thanks @asklar
