### ISSUE TITLE
MenuFlyout opening at pointer location not available

### ISSUE THREAD

**Issue by jechternach** [microsoft/react-native-xaml#162]
### Problem Description

Currently if I have a MenuFlyout the default behavior is not to have the flyout open at the pointer location, and there is no placement property that allows us to do so. 

### Steps To Reproduce

Create a MenuFlyout object for a GridViewItem without setting a placement property 
Right Click and open the flyout, expect the flyout to open at the pointer pressed location 

### Environment

```markdown
npx react-native info
```

**Comment by chrisglein** [comment]
@asklar Is there something preventing the [Placement](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.primitives.flyoutbase.placement?view=winrt-22000#Windows_UI_Xaml_Controls_Primitives_FlyoutBase_Placement) from `FlyoutBase` from working?

**Comment by asklar** [comment]
there is a missing feature from MenuFlyout where setting Placement=Auto will crash (!!) instead of using pointer position, for example.
The way to achieve this in RN would be to use jswinrt to get the pointer position and use the new API I added for MenuFlyout in react-native-xaml to pass the point

**Comment by asklar** [comment]
Closed by #171
