### ISSUE TITLE
Layout issue and onItemInvoked func of NavigationView

### ISSUE THREAD

**Issue by yiliachen** [microsoft/react-native-xaml#164]
Hi, your control library really helped me a lot, but I still have two questions, could you please help to check? Thank you so much!

**1. Layout issue**
I want 'Hello Word!' to display in the right panel of NavigationView, but it just displays below the last NavigationViewItem. Please check the attached screenshot for detail info, and I have put my code of NavigationView at the end. 
![nav1](https://user-images.githubusercontent.com/39049388/144366178-e4fa8e1e-6fd9-4d1f-afa8-0d6165de5b80.png)

**2. onItemInvoked func** 
Could you please guide how to reach the goal that right panel of NavigationView shows different pages when I select different NavigationViewItem?
**ItemInvoked func in Windows.UI.Xaml.Controls:**
public event TypedEventHandler<NavigationView,NavigationViewItemInvokedEventArgs> ItemInvoked;
**onItemInvoked fun in react-native-xaml:**
onItemInvoked?: (event: NativeSyntheticEvent<undefined>) => void;

As NavigationViewItemInvokedEventArgs in ItemInvoked pass the item I select, but onItemInvoked does not have such parameter, so how could I know which Item is selected?

**Here is my code of NavigationView:**

![Nav2](https://user-images.githubusercontent.com/39049388/144367151-2cd8eb25-11f5-49fb-a79d-c13aede96d0f.png)

**Comment by asklar** [comment]
For the first issue, that's a bug; going to fix it in #165.
For the second part of your question, you can use this:

```jsx
        <WinUI.NavigationView width={700} height={700} onItemInvoked={(e) => {
          const v = JSON.stringify(e.nativeEvent.args.invokedItem);
          alert(v); // this prints the selected navigation view item content, e.g. "Item 1".
        }}>
          <WinUI.NavigationViewItem content='Item 1' onTapped={() => setText('text #1')} priority={NavigationViewPriority.MenuItem}>
            <FontIcon glyph="&#xE790;" />
          </WinUI.NavigationViewItem>
          <WinUI.NavigationViewItem content='Item 2' onTapped={() => setText('text #2')} priority={NavigationViewPriority.FooterMenuItem}/>
          <TextBlock text={text} priority={NavigationViewPriority.Content}/>
        </WinUI.NavigationView>
```
