### ISSUE TITLE
XAML  MenuBar & MenuBarItem

### ISSUE THREAD

**Issue by dmagesh21** [microsoft/react-native-xaml#170]
When I add the MenuBar control, RNW app crashes (it disappears). 
Is this control working? I don't see this control in the examples.

I am able to use the MenuBarItem in the Grid control but it doesn't stack horizontally. I am not sure this is the way to do it though

**Comment by asklar** [comment]
@dmagesh21 can you provide a snippet of the jsx that you're using? Thanks!

**Comment by dmagesh21** [comment]
Adding MenuBarItem inside MenuBar control is causing the crash

const App = () => {
   return (
    <View>
      <MenuBar 
          background="black">
          <MenuBarItem title="Red"/>
          <MenuBarItem title="blue"/>
      </MenuBar>
    </View>
   );
 };

**Comment by dmagesh21** [comment]
Moving MenuBarItem outside MenuBar outputs like below
`const App = () => {
   return (
    <View>
      <MenuBar 
          background="black">
      </MenuBar>
      <MenuBarItem title="Red"/>
      <MenuBarItem title="blue"/>
    </View>
   );
 };
 `
![image](https://user-images.githubusercontent.com/90002094/149639974-fcdbf704-ef33-4185-99ca-99bffd01b153.png)

**Comment by dmagesh21** [comment]
@asklar @chiaramooney 
Can confirm the crash doesn't happen any more.
