### ISSUE TITLE
Hitting Errors Running Example App

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-xaml#180]
### Problem Description

When building example.sln, VS produces an error that the UseJsi() API does not exist. 

"class "winrt::Microsoft::ReactNative::ReactInstanceSettings" has no member "UseJsi"".

After commenting out this line the build succeeds, but when the app loads I get the following error: 

 Error: While trying to resolve module `react-native-xaml` from file `C:\Users\chiaramooney\react-native-xaml\example\App.tsx`, the package `C:\Users\chiaramooney\react-native-xaml\package\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`C:\Users\chiaramooney\react-native-xaml\package\lib\index.js`. Indeed, none of these files exist:

  * C:\Users\chiaramooney\react-native-xaml\package\lib\index.js(.native|.windows.js|.native.js|.js|.windows.json|.native.json|.json|.windows.ts|.native.ts|.ts|.windows.tsx|.native.tsx|.tsx)
  * C:\Users\chiaramooney\react-native-xaml\package\lib\index.js\index(.native|.windows.js|.native.js|.js|.windows.json|.native.json|.json|.windows.ts|.native.ts|.ts|.windows.tsx|.native.tsx|.tsx)

### Steps To Reproduce

1. Clone repo.
2. Open example.sln and build.
3. Comment out App.cpp line 23. 
4. Launch app.

### Expected Results

Successful build and launch of app. 

### Environment

```markdown
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 39.25 GB / 63.84 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    Visual Studio: 16.9.32002.222 (Visual Studio Enterprise 2019)
  Languages:
    Java: 1.8.0_282 - C:\Program Files\OpenJDK\openjdk-8u282-b08\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by chiaramooney** [comment]
Forgot `yarn build`.

**Comment by achipa** [comment]
I just ran into this myself. The defect is legit - you can't simply run the app as is without commenting out useJsi, which is not too friendly to people who are just getting familiar with RNfW and/or react-native-xaml.

// @asklar

**Comment by asklar** [comment]
UseJsi was the old property that was deprecated in 0.65 or so; I think we can just delete that line and it will work fine (`UseWebDebugger(false)` will do the right thing)

**Comment by chiaramooney** [comment]
Working for me with that line deleted. I'll make a PR!
