### ISSUE TITLE
Unable to set the foreground or font color of the MenuBarItem

### ISSUE THREAD

**Issue by dmagesh21** [microsoft/react-native-xaml#185]
### Problem Description

Unable to set the foreground or font color of the MenuBarItem

### Steps To Reproduce

Code used:
```jsx
<MenuBar background="red" >
  <MenuBarItem background="blue" foreground="white" title="File"> 
    <MenuFlyoutItem text="New">
      <KeyboardAccelerator modifiers={1} virtualKey={78}/>
    </MenuFlyoutItem>
    <MenuFlyoutItem text="Open">  
    </MenuFlyoutItem>
    <MenuFlyoutItem text="Save">  
    </MenuFlyoutItem>
    <MenuFlyoutItem text="Save As"> 
    </MenuFlyoutItem>
  </MenuBarItem> 
  <MenuBarItem title="View"/>
  <MenuBarItem title="Config"/>
  <MenuBarItem title="Help"/>
</MenuBar>
```

Output:
![MenuBar](https://user-images.githubusercontent.com/90002094/154254304-4b56a22e-b344-421d-9193-34bf78975513.JPG)

### Expected Results
Fonts color change to white color

### Environment

```markdown
npx react-native info

System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 10.17 GB / 31.69 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32002.261 (Visual Studio Community 2019), 16.11.32002.261 (Visual Studio Professional 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.3 => 0.66.3
    react-native-windows: 0.66.5 => 0.66.5
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by chrisglein** [comment]
@dmagesh21 The item color is going to be driven by the control's VisualStateManager, as it's affected by mouse hover and such. So setting a single color is often not enough. If you set Foreground it'd only affect the Idle state. To properly override the color you need to specify the whole set of styles for different states. I'm guessing as soon as you change focus or hover state it's affected?

There should be a mechanism to supply the styles through react-native-xaml, which is what I think you need? Detail [here](https://github.com/microsoft/react-native-xaml/blob/main/USAGE.md#lightweight-styling)

Let us know if that works out for you or if I'm misreading this.

**Comment by asklar** [comment]
@dmagesh21 The jsx markup you shared works fine for me:

![image](https://user-images.githubusercontent.com/22989529/155027182-4bdfb543-2472-4bcd-b569-c27935af2b13.png)

can you make sure you are using the latest react-native-xaml version?

**Comment by dmagesh21** [comment]
@asklar Interesting!  I have updated the react-native and react-native-xaml to the latest version but I still cannot get the foreground to be white.

_npx react-native info_
react: 17.0.2 => 17.0.2
react-native: 0.66.3 => 0.66.3
react-native-windows: 0.66.5 => 0.66.5

_package.json_
 "dependencies": {
    "@react-native-community/slider": "^4.2.0",
    "printf": "^0.6.1",
    "react": "17.0.2",
    "react-native": "0.66.3",
    "react-native-windows": "0.66.5",
    "react-native-xaml": "^0.0.54",
    "stream": "^0.0.2",
    "util": "^0.12.4"
  },

**Comment by chrisglein** [comment]
No updates since February. Are you unblocked?
