### ISSUE TITLE
Unable to set NativeButton width based on parent element

### ISSUE THREAD

**Issue by ReeceKenney** [microsoft/react-native-xaml#209]
### Problem Description

It seems we're not able to set the width of the NativeButton to stretch to fill all available space.

**Trying to achieve this:**
<img width="300" alt="image" src="https://user-images.githubusercontent.com/5323490/175302100-20a028e2-27d1-4751-88cc-c9cecaa08ed0.png">
**Current behaviour:**
![image](https://user-images.githubusercontent.com/5323490/175303386-8c51a3d1-0297-4623-83b2-c07f9ca75144.png)

In my current attempt, the buttons exist inside a Grid element but I have also tried this using a horizontal StackPanel with no success:

```
<Grid gridLayout={{ columns: ["*", "*"], rows: ["*"] }}>
    <Grid>
        <NativeButton 
          kind="Primary"
          text="Send"
        />
    </Grid>

    <Grid gridColumn={1}>
       <NativeButton 
          kind="Default"
          text="Cancel"
        />
    </Grid>
</Grid>
```
**Unsuccessful attempts:**

- Adding `width: '100%'` to the button elements via the `style` attribute. The width property of the button can only be `number` or `undefined` as defined in its type `NativeButtonStyle`. Even when changing the d.ts file to allow a string type, setting the width to 100% didn't work. 
- Setting `horizontalAlignment={HorizontalAlignment.Stretch}` on the button elements. This property doesn't exist on the button's type.
- Setting the parent element to `flex: 1, flexDirection: 'row'` via the `style` attribute and then setting the children to `flex: 1`
- Setting any variation of `alignItems`, `alignContent`, `alignSelf` and then setting the children to `justifyContent` on the parent element and/or the button elements. I wasn't able to see any of these properties make a change

Setting the width if the button elements to some fixed **number** value seems to be the only way I we can update the width. This isn't suitable if we don't know the fixed with value of the container. 

I was able to get the desired layout using actual `<Button>` elements but I'd like to use all the native style that comes with the NativeButton elements. Using the Button component means I'd need to style everything myself including hover states etc.

### Steps To Reproduce

Add a NativeButton element inside some element and try to make it take the full width.

### Expected Results

Ideally there would be a way to set button to take the fully width of the parent container

### Environment

```markdown
System:
    OS: Windows 10 10.0.25136
    CPU: (20) x64 Intel(R) Xeon(R) W-2155 CPU @ 3.30GHz
    Memory: 31.16 GB / 63.68 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.16299.0, 10.0.17134.0, 10.0.17763.0, 10.0.18362.0, 10.0.19023.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32602.291 (Visual Studio Enterprise 2019), 15.9.28307.2019 (Visual Studio Enterprise 2017), 17.2.32602.215 (Visual Studio Enterprise 2022)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by chrisglein** [comment]
@ReeceKenney Where is `NativeButton` defined? Is that a User Control in your app? Or some other toolkit?

**Comment by ReeceKenney** [comment]
Apologies Chris, I was under the impression that this was part of react-native-xaml. After reading your comment, I think it must belong to the wrapper package we're using in our project. 

No need for this question. Closing
