### ISSUE TITLE
Allow overriding package version through ExperimentalFeatures.props

### ISSUE THREAD

**Issue by MicrosoftNik** [microsoft/react-native-xaml#214]
### Summary

Currently, [Version.g.h](https://github.com/microsoft/react-native-xaml/blob/73cc7be0927296a3687066b6fa29e15acb74b2fe/package/windows/ReactNativeXaml/Codegen/Version.g.h) appears to be generated using the standard Version object with no option for override. 

[react-native-windows](https://github.com/microsoft/react-native-windows/blob/582373c6c5518f949c0a50ef156a76659c5112c5/.ado/scripts/setVersionEnvVars.js) allows for overriding the package version by specifying definitions for RNW_PKG_VERSION_STR, RNW_PKG_VERSION_MAJOR, RNW_PKG_VERSION_MINOR, RNW_PKG_VERSION_PATCH and RNW_PKG_VERSION_BUILD in ExperimentalFeatures.props. It would be useful to have this functionality present for react-native-xaml as well.

### Motivation

Currently our team is replacing the Version.g.h file with a patched version of the file to use our variable definitions. This is not ideal.

### Basic Example

Example of overriding the package version for react-native-windows in ExperimentalFeatures.props: 
```
 <ItemDefinitionGroup Condition="'$(BUILD_BUILDNUMBER)'!=''">
    <ResourceCompile>
      <PreprocessorDefinitions>
        RNW_PKG_VERSION_STR=$(BUILD_BUILDNUMBER);
        RNW_PKG_VERSION_MAJOR=$(BUILD_BUILDNUMBER.Split('.')[0]);
        RNW_PKG_VERSION_MINOR=$(BUILD_BUILDNUMBER.Split('.')[1]);
        RNW_PKG_VERSION_PATCH=$(BUILD_BUILDNUMBER.Split('.')[2]);
        RNW_PKG_VERSION_BUILD=$(BUILD_BUILDNUMBER.Split('.')[3]);
        %(PreprocessorDefinitions)
      </PreprocessorDefinitions>
    </ResourceCompile>
  </ItemDefinitionGroup>
```

**Comment by asklar** [comment]
@MicrosoftNik curious why you need to patch the version? the idea is we'd be able to correlate back to what the source was for that release.

**Comment by MicrosoftNik** [comment]
> @MicrosoftNik curious why you need to patch the version? the idea is we'd be able to correlate back to what the source was for that release.

Not 100% sure of the full reason (the person responsible for the change has left the company), but the reasoning written down is we would like to version it based on the the CI pipeline's build number.

**Comment by chrisglein** [comment]
There doesn't seem to be strong enough of a scenario for generally customizing this, and these macros have effects that have other existing dependencies. The fact that you're doing that for RNW may be causing issues (independent of this ask to add it to RN-Xaml as well). Can you give us more details on your requirements? Because this may not be the solution you're looking for.
