### ISSUE TITLE
Update projects to newer RNW versions

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-xaml#233]
Right now we target 0.64; we should update projects to a newer version so that we can still build them (e.g. pipelines are failing for the testrnx app because the certificate that comes from the project template has now expired)

**Comment by jonthysell** [comment]
PR #232 expands the test matrix for testing the CLI to run against in 0.64 and 0.69. So FYI that the versions tested should be updated when this is done.

**Comment by jonthysell** [comment]
Since we have customers on 0.67, I don't recommend setting the min version any higher than that.

**Comment by TatianaKapos** [comment]
closed via https://github.com/microsoft/react-native-xaml/pull/238
