### ISSUE TITLE
Package Failing to Build: No Matching Overload "SetPropValue"

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-xaml#250]
### Problem Description

react-native-xaml package is failing to build in Playground and React Native Gallery with error: "SetPropValue": No Matching Overloaded Function Found. 

Tested on 3 machines but only 2 machines are hitting the issue. 

### Steps To Reproduce

1. Clone react-native-gallery and build. 

### Expected Results

Successful build. 

### Environment

```markdown
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.25309
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 37.41 GB / 63.84 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17763.0, 10.0.18362.0, 10.0.19041.0, 10.0.22000.0, 10.0.22621.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 17.5.33414.496 (Visual Studio Enterprise 2022), 16.11.33328.57 (Visual Studio Enterprise 2019)
  Languages:
    Java: 11.0.16.1 - C:\Program Files\Eclipse Adoptium\jdk-11.0.16.101-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: ^0.70.0 => 0.70.0
    react-native-windows: ^0.70.0 => 0.70.4
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by asklar** [comment]
code builds fine in this repo (plus it only reproes in some but not all of your machines), so I imagine this is a machine setup problem. Closing as such.

**Comment by n-rocher** [comment]
I actually wanted to try react-native-xaml and I'm getting this issue.
After installing react-native-windows, I following the latest "Get Started", and I have been able to build and create my app.
But after installing this package, during the build I get this error and I can't do anything. I tried to rollback to 0.0.71 (which was working for me on another computer) but I still get this issue.

Do you know where this error comes from?

**Comment by asklar** [comment]
@n-rocher @chiaramooney  can you please paste the full error message? feel free to upload as a txt file if it's too long.

**Comment by n-rocher** [comment]
Sure, here is the log with --logging and the errors displayed in visual studio while generating "example".
![VISUAL-STUDIO](https://user-images.githubusercontent.com/5303586/224517840-a68e1da6-335c-41d9-9aae-5812e2aef05f.png)
[BUILD-ERROR-SetPropValue.txt](https://github.com/microsoft/react-native-xaml/files/10949744/BUILD-ERROR-SetPropValue.txt)

**Comment by asklar** [comment]
thanks @n-rocher ; it might be a compiler change then, I can repro it as well (though not in all devices, which leads me to believe it depends on whether one has applied the latest VS update or not). This may be a compiler bug but just so that we don't need to wait for a fix from msvc, I've put out a PR that should take care of it for this module.
