### ISSUE TITLE
Add support to specify ItemsPanel for ItemsControl elements such as GridView

### ISSUE THREAD

**Issue by pawisesa** [microsoft/react-native-xaml#252]
### Summary

We're looking to use GridView as a radio for our app but we need to have the GridView and its GridViewItems to take the full width of the container and currently the GridView as implemented in react-native-xaml doesn't do that and there doesn't seem to be an option to configure it to take up the full width.

Looking into the XAML tree we see that the ItemsPresenter used by the react-native-xaml GridView currently is using ItemsWrapGrid and searching around it seems like a solution to make a GridView take up the full width in XAML is to use ItemsStackPanel instead for the GridView's ItemsPanel [https://stackoverflow.com/a/35451090](https://stackoverflow.com/a/35451090), however there's no option to set this for react-native-xaml currently.

There are multiple different possible [Panel](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.panel?view=winrt-22621) but for now only ItemsWrapGrid and ItemsStackPanel  may be needed as options.

### Motivation

This is needed to make GridView and other ItemsControl able to take up the full width of it's container. This would be useful for any user of GridView.

**Comment by chrisglein** [comment]
There's a lot of work here. It may be more straightforward for you to create a custom GridView that has the configuration you want. That'd also future proof you from any other gaps in react-native-xaml.

**Comment by pawisesa** [comment]
Will be making a custom GridView that uses ItemsStackPanel as the ItemsPanel.
